# Generated by Django 2.0.7 on 2018-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('profilepic', models.ImageField(upload_to='images/profiles')),
            ],
        ),
    ]
